km_homepage:
    path:     /generate_barcode/{barcode}
    defaults: { _controller: KmBundle:Default:index }
    
km_barecode_test:
    path:     /barcode_test
    defaults: { _controller: KmBundle:Default:BarcodeTest }
    
km_dashboard:
    path:    /report
    defaults: { _controller: KmBundle:Default:dashboard }
    
km_documentation:
    path:    /
    defaults: { _controller: KmBundle:Default:front }
    
km_report_a:
    path:    /report_a
    defaults: { _controller: KmBundle:Default:reportA }
    
km_report_b:
    path:    /report_b
    defaults: { _controller: KmBundle:Default:reportB }
    
sales: 
  type: rest
  resource:     "TransactionBundle:Api"
  prefix:  api